[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "robo-pmac-driver"
version = "0.1.0"
description = "PMAC multi-axis control driver"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "forcedimension-core>=1.0.0",
    "numpy>=2.2.6",
    "paramiko>=4.0.0",
    "pymodbus==2.5.3",
    "pynput>=1.8.1",
    "pyyaml>=6.0.3",
    "pyzmq>=26.0.0",
    "scipy>=1.15.3",
]
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}
